name: Publish to TestPyPI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag (e.g. v1.2.3). If empty, uses current version metadata."
        required: false
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv with Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: false

      - name: Show versions
        run: |
          uv --version
          python --version

      - name: Create fake dev version
        run: |
          version=$(uv version --short) &&
          uv version $version$(date +%s)

      # Build the sdist and wheel into ./dist using uv
      - name: Build distribution
        run: uv build

      # Optionally verify the artifacts before upload
      - name: List built artifacts
        run: ls -l dist

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish:
    needs: build
    environment: testpypi

    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist

      # Upload to TestPyPI using OIDC (Trusted Publishing)
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          attestations: true
          skip-existing: true
