name: Publish to PyPI

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv with Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: false

      - name: Show versions
        run: |
          uv --version
          python --version

      # Build the sdist and wheel into ./dist using uv
      - name: Build distribution
        run: uv build

      # Optionally verify the artifacts before upload
      - name: List built artifacts
        run: ls -l dist

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish:
    needs: build
    environment: pypi

    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist

      # Upload to PyPI using OIDC (Trusted Publishing)
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
